apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-file-app
  labels:
    app: node-file-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-file-app
  template:
    metadata:
      labels:
        app: node-file-app
    spec:
      containers:
        - name: my-node-app-container
          image: sambhavanisantosh322/node-file-app:v1
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: my-vol
              mountPath: "/app/emails.txt"
      volumes:
        - name: my-vol
          hostPath:
            path: /emails.txt
            type: FileOrCreate

---

kind: Service
apiVersion: v1
metadata:
  name: service-node-file-app
spec:
  ports:
    - name: http
      port: 4000
      targetPort: 3000
  selector:
    app: node-file-app
  type: LoadBalancer
