apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-node-app
  labels:
    app: node-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
      - name: my-node-app-container
        image: sambhavanisantosh322/node-demo-app:v1
        ports:
        - containerPort: 3000
